---

- name: "Ensure Debian/Ubuntu Linux packages have been patched"
  apt: update_cache=yes cache_valid_time=3600
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  sudo: yes
  when: ansible_os_family == "Debian" or ansible_os_family == 'Ubuntu'

- name: retry if needed using command apt-get update
  command: apt-get update
  sudo: yes
  when: apt_result|failed and (ansible_os_family == "Debian" or ansible_os_family == 'Ubuntu')

- name: "Set timezone to America/New_York"
  timezone:
    name: America/New_York
  when: ansible_os_family == "Amazon"

- name: "Remove AWS System Manager, OSSEC had lot of errors with it"
  yum:
    name: amazon-ssm-agent.x86_64
    state: absent
  when: ansible_os_family == 'Amazon'

# cat /etc/os-release && sestatus